//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OctopathBossRandomizerRefactored.rc
//
#define APP_NAME                        1
#define APP_CLASS                       2
#define VERSION                         3
#define EDITBOX                         4
#define FILEBUTTON                      5
#define RANDOMIZEBUTTON                 6
#define SEEDBOX                         7
#define CONFIGSYNC                      8
#define MAINBOSSOPTIONS                 9
#define SIDEBOSSOPTIONS                 10
#define SCALINGOPTIONS                  11
#define TABMENU                         12
#define DESCRIPTIONSTRING               13
#define MAIN_MIXTEXT                    100
#define MAIN_DEFAULTMIX                 101
#define IDI_SMALLICON                   102
#define MAIN_MIX24                      102
#define IDD_FORCEBOSS                   102
#define IDR_MAIN                        103
#define MAIN_MIX14                      103
#define MAIN_SHRINETEXT                 104
#define MAIN_NOSHRINE                   105
#define MAIN_RANDOMSHRINE               106
#define MAIN_INCLUDESHRINE              107
#define MAIN_GATETEXT                   108
#define MAIN_NOGATE                     109
#define MAIN_RANDOMGATE                 110
#define MAIN_INCLUDEGATE                111
#define MAIN_GALDERATEXT                112
#define MAIN_NOGALDERA                  113
#define MAIN_INCLUDEGALDERA             114
#define MAIN_DUPLICATETEXT              115
#define MAIN_NODUPLICATE                116
#define MAIN_ALLOWDUPLICATE             117
#define MAIN_WINTEXT                    118
#define MAIN_PCWIN                      119
#define MAIN_GALDERAWIN                 120
#define MAIN_SPECIALTEXT                121
#define MAIN_FULLRANDOM                 122
#define MAIN_SOLORANDOM                 123
#define MAIN_FORCEBOSS                  124
#define MAIN_FORCEBOSSOPTION            125
#define MAIN_FORCEPCTEXT                126
#define MAIN_NOFORCEPC                  127
#define MAIN_FORCEPC                    128
#define MAIN_SPECIFICPC                 129
#define MAIN_SPECIFICPCOPTION           130
#define IDD_CONFIGSYNC                  137
#define MAIN_DEFAULTMIXSTRING           151
#define MAIN_MIX24STRING                152
#define MAIN_MIX14STRING                153
#define MAIN_NOSHRINESTRING             155
#define MAIN_RANDOMSHRINESTRING         156
#define MAIN_INCLUDESHRINESTRING        157
#define MAIN_NOGATESTRING               159
#define MAIN_RANDOMGATESTRING           160
#define MAIN_INCLUDEGATESTRING          161
#define MAIN_NOGALDERASTRING            163
#define MAIN_INCLUDEGALDERASTRING       164
#define MAIN_NODUPLICATESTRING          166
#define MAIN_ALLOWSUPLICATESTRING       167
#define MAIN_ALLOWDUPLICATESTRING       167
#define MAIN_PCWINSTRING                169
#define MAIN_GALDERAWINSTRING           170
#define MAIN_NOFULLRANDOMSTRING         171
#define MAIN_FULLRANDOMSTRING           172
#define MAIN_NOSOLORANDOMSTRING         173
#define MAIN_SOLORANDOMSTRING           174
#define MAIN_NOFORCESTRING              175
#define MAIN_FORCESTRING                176
#define MAIN_NOFORCEPCSTRING            177
#define MAIN_FORCEPCSTRING              178
#define MAIN_FORCERANDOMPCSTRING        178
#define MAIN_FORCESPECIFICPCSTRING      179
#define SIDE_ENABLE                     201
#define SIDE_RINGOPTIONS                202
#define SIDE_NORING                     203
#define SIDE_SAMERING                   204
#define SIDE_MIXRING                    205
#define SIDE_MIXBOSS                    206
#define SIDE_PREBOSSOPTIONS             207
#define SIDE_NOPREBOSS                  208
#define SIDE_PREBOSSRANDO               209
#define SIDE_PREBOSSMIX                 210
#define SIDE_BOSSCHANCETEXT             211
#define SIDE_BOSSCHANCE                 212
#define SIDE_BOSSCHANCERANGE            213
#define SIDE_PREBOSSCHANCETEXT          214
#define SIDE_PREBOSSCHANCE              215
#define SIDE_PREBOSSCHANCERANGE         216
#define SIDE_NOENABLESTRING             251
#define SIDE_ENABLESTRING               252
#define SIDE_NORINGSTRINg               253
#define SIDE_NORINGSTRING               253
#define SIDE_SAMERINGSTRING             254
#define SIDE_MIXRINGSTRING              255
#define SIDE_MIXBOSSSTRING              256
#define SIDE_NOPREBOSSSTRING            257
#define SIDE_PREBOSSRANDOSTRING         258
#define SIDE_PREBOSSMIXSTRING           259
#define SIDE_BOSSCHANCESTRING           260
#define SIDE_PREBOSSCHANCESTRING        261
#define SCALE_ENABLE                    301
#define SCALE_HARDMODE                  302
#define SCALE_RANDOTEXT                 303
#define SCALE_RANDO                     304
#define SCALE_RANDOBOX                  305
#define SCALE_RANDORANGE                306
#define SCALE_EXPTEXT                   307
#define SCALE_EXP                       308
#define SCALE_EXPBOX                    309
#define SCALE_EXPRANGE                  310
#define SCALE_JPTEXT                    311
#define SCALE_JP                        312
#define SCALE_JPBOX                     313
#define SCALE_JPRANGE                   314
#define SCALE_BOSSLOC                   315
#define SCALE_NOENABLESTRING            351
#define SCALE_ENABLESTRING              352
#define SCALE_NOHARDMODESTRING          353
#define SCALE_HARDMODESTRING            354
#define SCALE_RANDOSTRING               355
#define SCALE_EXPSTRING                 356
#define SCALE_JPSTRING                  357
#define SCALE_NOBOSSLOCSTRING           358
#define SCALE_BOSSLOCSTRING             359
#define IDC_COMBOTIER1                  1001
#define IDC_COMBOTIER2                  1002
#define IDC_COMBOTIER3                  1003
#define IDC_COMBOTIER4                  1005
#define IDC_COMBOTIER5                  1006
#define IDC_COMBOTIER6                  1007
#define IDC_FORCEGALDERA                1008
#define IDC_CONFIGSYNCEDIT              1009
#define IDC_CONFIGERROR                 1010
#define ID_TEST_ABOUT                   40001
#define ID_TEST_HELP                    40002
#define IDR_ABOUT                       40003
#define IDR_HELP                        40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
